// <auto-generated />
using System;
using BudgetApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetApi.Migrations
{
    [DbContext(typeof(BudgetDBContext))]
    [Migration("20221006081954_budget")]
    partial class budget
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BudgetApi.Data.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpensesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IncomeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TotalID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryID");

                    b.HasIndex("ExpensesID");

                    b.HasIndex("IncomeID");

                    b.HasIndex("TotalID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("1025d791-fc45-4373-8de7-2ba547b873e0"),
                            ExpensesID = new Guid("49c37889-c7fc-4d0e-8892-1be05ff2735d"),
                            IncomeID = new Guid("7589e453-227a-425b-bffa-6c260faa5bc2"),
                            Name = "Rent",
                            TotalID = new Guid("636bf07e-d900-4f64-87b7-f46efaa8e90f")
                        },
                        new
                        {
                            CategoryID = new Guid("e2b53e13-9ce2-4e1c-aeb9-05faf7c4f461"),
                            ExpensesID = new Guid("49c37889-c7fc-4d0e-8892-1be05ff2735d"),
                            IncomeID = new Guid("7589e453-227a-425b-bffa-6c260faa5bc2"),
                            Name = "Salary",
                            TotalID = new Guid("636bf07e-d900-4f64-87b7-f46efaa8e90f")
                        },
                        new
                        {
                            CategoryID = new Guid("faeec15d-c9c9-47f6-9453-3dace77ef237"),
                            ExpensesID = new Guid("49c37889-c7fc-4d0e-8892-1be05ff2735d"),
                            IncomeID = new Guid("7589e453-227a-425b-bffa-6c260faa5bc2"),
                            Name = "Other",
                            TotalID = new Guid("636bf07e-d900-4f64-87b7-f46efaa8e90f")
                        });
                });

            modelBuilder.Entity("BudgetApi.Data.Expenses", b =>
                {
                    b.Property<Guid>("ExpensesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ExpensesID");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ExpensesID = new Guid("49c37889-c7fc-4d0e-8892-1be05ff2735d"),
                            Date = new DateTime(2022, 10, 6, 10, 19, 54, 756, DateTimeKind.Local).AddTicks(9715),
                            Name = "Appartment",
                            Value = 670.0
                        });
                });

            modelBuilder.Entity("BudgetApi.Data.Income", b =>
                {
                    b.Property<Guid>("IncomeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("IncomeID");

                    b.ToTable("Income");

                    b.HasData(
                        new
                        {
                            IncomeID = new Guid("7589e453-227a-425b-bffa-6c260faa5bc2"),
                            Date = new DateTime(2022, 10, 6, 10, 19, 54, 756, DateTimeKind.Local).AddTicks(9749),
                            Name = "Money B.V",
                            Value = 2950.0
                        });
                });

            modelBuilder.Entity("BudgetApi.Data.Total", b =>
                {
                    b.Property<Guid>("TotalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("TotalID");

                    b.ToTable("Total");

                    b.HasData(
                        new
                        {
                            TotalID = new Guid("636bf07e-d900-4f64-87b7-f46efaa8e90f"),
                            Date = new DateTime(2022, 10, 6, 10, 19, 54, 756, DateTimeKind.Local).AddTicks(9752),
                            Name = "Money B.V",
                            Value = 2280.0
                        });
                });

            modelBuilder.Entity("BudgetApi.Data.Category", b =>
                {
                    b.HasOne("BudgetApi.Data.Expenses", null)
                        .WithMany("Categories")
                        .HasForeignKey("ExpensesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetApi.Data.Income", null)
                        .WithMany("Categories")
                        .HasForeignKey("IncomeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetApi.Data.Total", null)
                        .WithMany("Categories")
                        .HasForeignKey("TotalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetApi.Data.Expenses", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("BudgetApi.Data.Income", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("BudgetApi.Data.Total", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
