// <auto-generated />
using System;
using BudgetApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetApi.Migrations
{
    [DbContext(typeof(IncomeDBContext))]
    [Migration("20220911105412_income")]
    partial class income
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BudgetApi.Data.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Income");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(758),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(795),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(797),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(798),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(800),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(801),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(803),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(804),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(806),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(808),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(809),
                            Name = "testIncome",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 9, 11, 12, 54, 12, 329, DateTimeKind.Local).AddTicks(810),
                            Name = "testIncome",
                            Value = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
