// <auto-generated />
using System;
using BudgetApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetApi.Migrations.TotalDB
{
    [DbContext(typeof(TotalDBContext))]
    partial class TotalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BudgetApi.Data.Total", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Total");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9810),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9842),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9845),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9847),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9848),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9850),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9852),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9854),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9856),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9858),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9859),
                            Name = "testTotal",
                            Value = 0.0
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 9, 11, 13, 52, 19, 953, DateTimeKind.Local).AddTicks(9861),
                            Name = "testTotal",
                            Value = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
